### ISSUE TITLE
Support for simulation from a model?

### ISSUE THREAD

**Issue by cboettig** [greta-dev/greta#286] opened 2019-06-17 18:01 UTC
I'd love to have a `simulate()` method to simulate samples from a model.  (This is particularly nice for teaching / testing where you can simulate from a model object with fixed parameters and then do mcmc on the model object to compare inference.  Could also be a nice syntax for simulating large stochastic models generally? [nimble has support for this](https://github.com/cboettig/nimbios-transients/blob/93db66edce7d6a92d3ef178c9b3229e20a365c0e/code/nimble.Rmd#L21-L39).  Does that make any sense?

**Comment by goldingn** [comment] 2019-06-18 03:39
Yes, this is something I'd love to have too. It would be useful for automating prior predictive checks as well as for teaching in an Intro Bayes (with greta) course we've developed, which starts with simulating data. This is a duplicate of #269, and see [a related discussion on the forum](https://forum.greta-stats.org/t/introducing-rgreta/83).

Note you _can_ currently simulate from a model with priors (provided there are no discrete variables) byjust omitting the observed data statement (the `distribution(data) <- ` bit) and doing MCMC. Then greta will sample from the prior density. Though this isn't ideal since a) it doesn't give you samples of your observations, and b) these are correlated MCMC samples when we could do IID samples more efficiently (though in practice HMC is pretty efficieent in sampling from priors).

Adding the ability to simulate IID from priors (which is needed for this) would also make automatic specification of initial values easier for most Bayesian models.

**Comment by Voltemand** [comment] 2019-06-18 08:57
I do have a (pretty stale) branch starting to implement this idea which I'm happy to revisit if there is interest.

I've just been quite busy at the moment - full time job + writing a paper with some people in my spare time. 

If this is something you would like/ are willing to review pull request for @goldingn then I would be happy to dust off my branch.

**Comment by goldingn** [comment] 2019-06-29 04:56
It would be great if you could.

But no worries if you don't have time. As you'll have noticed from the drop off in my commits, I'm in the same boat! that should change soon though. I'm itching for a coding retreat and to get a bunch of features like this implemented.

**Comment by goldingn** [comment] 2019-06-29 04:56
closing as duplicate of #269

**Closed by goldingn** 2019-06-29 04:56 UTC
