### ISSUE TITLE
Survival model with censoring

### ISSUE THREAD

**Issue by fkgruber** [greta-dev/greta#215] opened 2018-08-14 20:17 UTC
Hi
Has there been any progress in survival model support. It would be helpful to at least have some parametrics models like Weibull but it needs to support censored cases.

thanks
FKG

**Comment by goldingn** [comment] 2018-09-05 20:11
I'm doing some issue tidying, so closing this as it's a duplicate of #42. Please post there of you have any questions, comments or would like to flag any progress you've made!

**Closed by goldingn** 2018-09-05 20:11 UTC
