### ISSUE TITLE
analyses section in the documentation

### ISSUE THREAD

**Issue by shuckle16** [greta-dev/greta#270] opened 2019-03-02 20:40 UTC
Hello,

This is an amazing package! Thank you for developing it.

I was reading through the documentation and noticed the figures in the analyses section are not showing up https://greta-stats.org/articles/analyses/election_88.html and https://greta-stats.org/articles/analyses/eight_schools.html

I looked through the docs on github, and it appears the relative file paths of the png's aren't referencing the correct images.
https://github.com/greta-dev/greta/tree/master/docs/articles/analyses

Thanks again for your work!

**Comment by goldingn** [comment] 2019-03-06 06:39
Thanks!

Yes something went awry when I switched to hosting this with netlify (though the timing could be unrelated).

**Comment by Voltemand** [comment] 2019-03-06 11:22
I would note that this is technically a duplicate of #243 (and #258 though that was closed).

**Comment by goldingn** [comment] 2019-03-06 11:28
Ah yes, I thought there was a duplicate, but couldn't find it when I searched. I'll close this one then.

**Closed by goldingn** 2019-03-06 11:28 UTC
